### ISSUE TITLE
Plugin crash: panic: ConfigSpec failed: gob: type cty.Type has no exported fields

### ISSUE THREAD

**Issue by rickard-von-essen** [jboero/packer-plugin-nspawn#15]
Building the plugin from 7e07c8a51bca6e8c4 and using Packer 1.8.6.
And then trying to run the `example/` with `packer init -upgrade && packer build build.pkr.hcl` result in a crash:

```
panic: ConfigSpec failed: gob: type cty.Type has no exported fields [recovered]
        panic: ConfigSpec failed: gob: type cty.Type has no exported fields

goroutine 1 [running]:
log.Panic({0xc000a9e758?, 0x8f34a80?, 0xc000a9e7b8?})
        log/log.go:384 +0x65
github.com/hashicorp/packer/packer.(*cmdBuilder).checkExit(0x417f70?, {0x42476a0, 0xc000378080}, 0x0)
        github.com/hashicorp/packer/packer/cmd_builder.go:47 +0x7f
github.com/hashicorp/packer/packer.(*cmdBuilder).ConfigSpec.func1()
        github.com/hashicorp/packer/packer/cmd_builder.go:19 +0x39
panic({0x42476a0, 0xc000378080})
        runtime/panic.go:884 +0x213
github.com/hashicorp/packer-plugin-sdk/rpc.(*commonClient).ConfigSpec(0xc0003b45a0)
        github.com/hashicorp/packer-plugin-sdk@v0.4.0/rpc/common.go:47 +0x297
github.com/hashicorp/packer/packer.(*cmdBuilder).ConfigSpec(0x0?)
        github.com/hashicorp/packer/packer/cmd_builder.go:22 +0x65
github.com/hashicorp/packer/hcl2template.decodeHCL2Spec({0x5a55f30, 0xc000c38990}, 0x52a6e54?, {0x7f56d8a4a6a0?, 0xc000013020?})
        github.com/hashicorp/packer/hcl2template/decode.go:17 +0x39
github.com/hashicorp/packer/hcl2template.(*PackerConfig).startBuilder(0xc0003e9900, {{{0xc0006e25a7, 0xe}, {0xc0006e25b6, 0xd}}, {0x0, 0x0}, {0x5a55f30, 0xc000c38990}}, 0xc000c403d8)
        github.com/hashicorp/packer/hcl2template/types.source.go:117 +0x1cd
github.com/hashicorp/packer/hcl2template.(*PackerConfig).GetBuilds(0xc0003e9900, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, ...}, ...})
        github.com/hashicorp/packer/hcl2template/types.packer_config.go:662 +0xf10
github.com/hashicorp/packer/command.(*BuildCommand).RunContext(0xc000a2ab40, {0x5a556a8?, 0xc0000d60f0}, 0xc000348ab0)
        github.com/hashicorp/packer/command/build.go:110 +0x23d
github.com/hashicorp/packer/command.(*BuildCommand).Run(0xc000a2ab40, {0xc00011a170, 0x1, 0x1})
        github.com/hashicorp/packer/command/build.go:38 +0xc5
github.com/mitchellh/cli.(*CLI).Run(0xc00038e140)
        github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.wrappedMain()
        github.com/hashicorp/packer/main.go:262 +0xcc5
main.realMain()
        github.com/hashicorp/packer/main.go:49 +0xf5
main.main()
        github.com/hashicorp/packer/main.go:35 +0x19



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by rickard-von-essen** [comment]
[crash.log](https://gist.github.com/rickard-von-essen/f4ac93f740dac9bfb35e1b2e57754941)
